# Generated by Django 5.1.3 on 2025-01-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_cartdb_orderdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdb',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
